Readme suggestions
levyadams/gulp-browserify-browser-sync pull request #1
Opened 2018-06-20 19:52 UTC by flaura42

Added info and step.  Feel free to change/ignore.

2018-06-20 20:41 UTC, levyadams requested changes
Looks good. We can remove the part at the end about not knowing about the security stuff.

2018-06-23 17:40 UTC, levyadams commented
@flaura42 did you want to do this part? :D

2018-06-23 20:30 UTC, flaura42 commented
Changes made!

2018-06-23 21:54 UTC, levyadams approved these changes

2018-06-24 04:31 UTC, merged